-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 15:14:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mawiicom__mawii
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mawiicom__mawii
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mawiicom__mawii` DEFAULT CHARACTER SET utf8 ;
USE `mawiicom__mawii` ;

-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`header` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `sub_titulo` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`header_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`header_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` TEXT NOT NULL,
  `icon` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`nosotros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`nosotros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `video` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `facebook` VARCHAR(60) NOT NULL,
  `twitter` VARCHAR(60) NOT NULL,
  `instagram` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`menu_pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`menu_pagina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `icon` VARCHAR(60) NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mawiicom__mawii`.`head`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mawiicom__mawii`.`head` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(60) NOT NULL,
  `description` TEXT NULL,
  `keywords` TEXT NULL,
  `logo` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
